/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CursoDTO;

/**
 * Formulario encargado
 * de confirmar el guardado
 * de un curso dentro del sistema.
 * 
 * Permite validar la acción
 * antes de registrar
 * el curso definitivamente.
 * 
 * @author PC GAMER MASTER RACE
 */
public class ConfirmacionCursoFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmacionCursoFORM.class.getName());
    private final ControlNavegacion control;
    private final CursoDTO curso;

    /**
    * Constructor del formulario
    * de confirmación de curso.
    * 
    * Inicializa los componentes
    * y recibe el curso
    * a guardar.
    * 
    * @param control Controlador
    * de navegación del sistema.
    * @param curso Curso
    * a confirmar.
    */
    public ConfirmacionCursoFORM(ControlNavegacion control, CursoDTO curso) {
        this.control = control;
        this.curso = curso;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        lblConfirmar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblConfirmacionDelGurdadoHoraio = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));
        pnlNegro.setForeground(new java.awt.Color(242, 242, 242));

        lblConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblConfirmar.setForeground(new java.awt.Color(242, 242, 242));
        lblConfirmar.setText("¿CONFIRMAR?");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblConfirmacionDelGurdadoHoraio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblConfirmacionDelGurdadoHoraio.setForeground(new java.awt.Color(242, 242, 242));
        lblConfirmacionDelGurdadoHoraio.setText("¿Confirmar El Guardado Del Horario?");

        btnSi.setBackground(new java.awt.Color(255, 0, 0));
        btnSi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSi.setForeground(new java.awt.Color(255, 255, 255));
        btnSi.setText("SI");
        btnSi.addActionListener(this::btnSiActionPerformed);

        btnNO.setBackground(new java.awt.Color(255, 0, 0));
        btnNO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNO.setForeground(new java.awt.Color(255, 255, 255));
        btnNO.setText("NO");
        btnNO.addActionListener(this::btnNOActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                        .addComponent(lblConfirmar)
                        .addGap(358, 358, 358))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                        .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNegroLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblConfirmacionDelGurdadoHoraio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(245, 245, 245))))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfirmacionDelGurdadoHoraio)
                .addGap(143, 143, 143)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSi)
                    .addComponent(btnNO))
                .addContainerGap(499, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Evento ejecutado
    * al presionar el botón sí.
    * 
    * Guarda el curso
    * y navega a la pantalla
    * de éxito.
    * 
    * @param evt Evento generado
    * por el botón sí.
    */
    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // Guarda el curso y navega a exito
        CursoDTO guardado = control.agregarCurso(curso);
        if (guardado != null) {
            control.navegarExitoCurso(guardado);
        }
    }//GEN-LAST:event_btnSiActionPerformed

    /**
    * Evento ejecutado
    * al presionar el botón no.
    * 
    * Cancela la operación
    * y regresa al menú
    * del administrador.
    * 
    * @param evt Evento generado
    * por el botón no.
    */
    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        control.navegarMenuAdmin();
    }//GEN-LAST:event_btnNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNO;
    private javax.swing.JButton btnSi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmacionDelGurdadoHoraio;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
