/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.HorarioDTO;

/**
 * Formulario encargado
 * de confirmar el guardado
 * de un horario dentro del sistema.
 * 
 * Permite validar la acción
 * antes de registrar
 * el horario definitivamente.
 * 
 * @author PC GAMER MASTER RACE
 */
public class ConfirmacionHorarioFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmacionHorarioFORM.class.getName());
    private final ControlNavegacion control;
    private final HorarioDTO horarioDTO;

    /**
    * Constructor del formulario
    * de confirmación de horario.
    * 
    * Inicializa los componentes
    * y recibe el horario
    * a guardar.
    * 
    * @param control Controlador
    * de navegación del sistema.
    * @param horarioDTO Horario
    * a confirmar.
    */
    public ConfirmacionHorarioFORM(ControlNavegacion control, HorarioDTO horarioDTO) {
        this.control    = control;
        this.horarioDTO = horarioDTO;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblConfirmacionDelGurdadoHoraio = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        btnNO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("¿CONFIRMAR?");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblConfirmacionDelGurdadoHoraio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblConfirmacionDelGurdadoHoraio.setForeground(new java.awt.Color(242, 242, 242));
        lblConfirmacionDelGurdadoHoraio.setText("¿Confirmar El Guardado Del Horario?");

        btnSi.setBackground(new java.awt.Color(255, 0, 0));
        btnSi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSi.setForeground(new java.awt.Color(255, 255, 255));
        btnSi.setText("SI");
        btnSi.addActionListener(this::btnSiActionPerformed);

        btnNO.setBackground(new java.awt.Color(255, 0, 0));
        btnNO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNO.setForeground(new java.awt.Color(255, 255, 255));
        btnNO.setText("NO");
        btnNO.addActionListener(this::btnNOActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnSi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(btnNO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmacionDelGurdadoHoraio)
                .addGap(279, 279, 279))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblConfirmacionDelGurdadoHoraio)
                .addGap(106, 106, 106)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSi)
                    .addComponent(btnNO))
                .addGap(0, 511, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Evento ejecutado
    * al presionar el botón sí.
    * 
    * Guarda el horario
    * y navega a la pantalla
    * de éxito.
    * 
    * @param evt Evento generado
    * por el botón sí.
    */
    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // Guarda el horario y navega a exito
        HorarioDTO guardado = control.agregarHorario(horarioDTO);
        if (guardado != null) {
            control.navegarExitoHorario();
        }
    }//GEN-LAST:event_btnSiActionPerformed

    /**
    * Evento ejecutado
    * al presionar el botón no.
    * 
    * Cancela la operación
    * y regresa al menú
    * del administrador.
    * 
    * @param evt Evento generado
    * por el botón no.
    */
    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        control.navegarMenuAdmin();
    }//GEN-LAST:event_btnNOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNO;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmacionDelGurdadoHoraio;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
