/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CursoDTO;
import com.mycompany.fitlifegym_dtos.DisponibilidadCursoDTO;
import com.mycompany.fitlifegym_dtos.ImagenDTO;
import com.mycompany.fitlifegym_presentacion.guardarImagen.GurdadorImagenCarpeta;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Formulario encargado
 * de editar cursos
 * existentes del sistema.
 * 
 * Permite modificar la información
 * de un curso, incluyendo
 * imagen, descripción y cupo.
 * 
 * @author PC GAMER MASTER RACE
 */
public class EditarCursosFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCursosFORM.class.getName());
    private final ControlNavegacion control;
    private final CursoDTO cursoOriginal;
    private String rutaImagenSeleccionada = "";

    /**
    * Constructor del formulario
    * de edición de cursos.
    * 
    * Inicializa los componentes
    * y carga los datos
    * del curso seleccionado.
    * 
    * @param control Controlador
    * de navegación del sistema.
    * @param curso Curso
    * a editar.
    */
    public EditarCursosFORM(ControlNavegacion control, CursoDTO curso) {
        this.control = control;
        this.cursoOriginal = curso;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        precargarDatos();
    }

    /**
    * Precarga los datos
    * del curso seleccionado
    * dentro del formulario.
    * 
    * Muestra la información
    * actual del curso
    * a editar.
    */
    private void precargarDatos() {
        txtNombreDelCurso.setText(cursoOriginal.getNombre());
        txtDescripcion.setText(cursoOriginal.getDescripcion());
        txtCupoMinimo.setText(String.valueOf(cursoOriginal.getCupoMinimo()));

        if (cursoOriginal.getImagen() != null && cursoOriginal.getImagen().getRuta() != null && !cursoOriginal.getImagen().getRuta().isEmpty()) {
            rutaImagenSeleccionada = cursoOriginal.getImagen().getRuta();
            mostrarPreview(rutaImagenSeleccionada);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblEditarCurso = new javax.swing.JLabel();
        lblNombreDelCurso = new javax.swing.JLabel();
        txtNombreDelCurso = new javax.swing.JTextField();
        btnSeleccionarImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblPreviwe = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblCupoMinimo = new javax.swing.JLabel();
        txtCupoMinimo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        jSeparator2.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator2.setForeground(new java.awt.Color(225, 6, 0));

        lblEditarCurso.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblEditarCurso.setForeground(new java.awt.Color(242, 242, 242));
        lblEditarCurso.setText("EDITAR CURSO");

        lblNombreDelCurso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombreDelCurso.setForeground(new java.awt.Color(242, 242, 242));
        lblNombreDelCurso.setText("Nombre del Curso:");

        txtNombreDelCurso.setBackground(new java.awt.Color(99, 99, 99));
        txtNombreDelCurso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNombreDelCurso.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreDelCurso.addActionListener(this::txtNombreDelCursoActionPerformed);

        btnSeleccionarImagen.setBackground(new java.awt.Color(99, 99, 99));
        btnSeleccionarImagen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSeleccionarImagen.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarImagen.setText("Seleccionar Imagen");
        btnSeleccionarImagen.addActionListener(this::btnSeleccionarImagenActionPerformed);

        lblImagen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblImagen.setForeground(new java.awt.Color(242, 242, 242));
        lblImagen.setText("Imagen:");

        lblPreviwe.setBackground(new java.awt.Color(64, 64, 64));
        lblPreviwe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreviwe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPreviwe.setOpaque(true);
        lblPreviwe.setPreferredSize(new java.awt.Dimension(150, 130));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(242, 242, 242));
        lblDescripcion.setText("Descripcion:");

        txtDescripcion.setBackground(new java.awt.Color(99, 99, 99));
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        lblCupoMinimo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCupoMinimo.setForeground(new java.awt.Color(242, 242, 242));
        lblCupoMinimo.setText("Cupo Minimo:");

        txtCupoMinimo.setBackground(new java.awt.Color(99, 99, 99));
        txtCupoMinimo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCupoMinimo.setForeground(new java.awt.Color(255, 255, 255));
        txtCupoMinimo.addActionListener(this::txtCupoMinimoActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(245, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(245, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEditarCurso)
                .addGap(291, 291, 291))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen)
                            .addComponent(lblDescripcion)
                            .addComponent(txtNombreDelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCupoMinimo)
                                .addGap(18, 18, 18)
                                .addComponent(txtCupoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombreDelCurso)
                            .addComponent(btnSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEditarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreDelCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreDelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarImagen)
                .addGap(18, 18, 18)
                .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCupoMinimo)
                    .addComponent(txtCupoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDelCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDelCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDelCursoActionPerformed

    /**
    * Evento ejecutado
    * al seleccionar una imagen
    * para el curso.
    * 
    * Permite elegir una imagen
    * desde el explorador
    * de archivos.
    * 
    * @param evt Evento generado
    * por el botón seleccionar imagen.
    */
    private void btnSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarImagenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png"));
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                rutaImagenSeleccionada = GurdadorImagenCarpeta.guardarImagen(archivo);
                mostrarPreview(rutaImagenSeleccionada);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar imagen: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
    * Muestra una vista previa
    * de la imagen seleccionada.
    * 
    * @param ruta Ruta
    * de la imagen.
    */
    private void mostrarPreview(String ruta) {
        ImageIcon icon = GurdadorImagenCarpeta.cargarImagen(ruta, lblPreviwe.getWidth(), lblPreviwe.getHeight());
            if (icon != null) {
                lblPreviwe.setIcon(icon);
                lblPreviwe.setText("");
            } else {
                lblPreviwe.setText("Error al cargar imagen");
                lblPreviwe.setIcon(null);
            }
    }//GEN-LAST:event_btnSeleccionarImagenActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCupoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCupoMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCupoMinimoActionPerformed

    /**
    * Evento ejecutado
    * al presionar el botón guardar.
    * 
    * Valida los datos capturados
    * y actualiza el curso
    * dentro del sistema.
    * 
    * @param evt Evento generado
    * por el botón guardar.
    */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombreDelCurso.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return;
        }

        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción es obligatoria.");
            return;
        }

        if (txtCupoMinimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El cupo mínimo es obligatorio.");
            return;
        }

        try {
            ImagenDTO imagenDTO = cursoOriginal.getImagen();
            if (!rutaImagenSeleccionada.isEmpty()) {
                imagenDTO = new ImagenDTO(rutaImagenSeleccionada);
            }

            CursoDTO cursoEditado = new CursoDTO(cursoOriginal.getIdCurso(), txtNombreDelCurso.getText().trim(), imagenDTO, txtDescripcion.getText().trim(), Integer.parseInt(txtCupoMinimo.getText().trim()), DisponibilidadCursoDTO.DISPONIBLE);

            CursoDTO guardado = control.editarCurso(cursoEditado);

            if (guardado != null) {
                JOptionPane.showMessageDialog(this, "¡Curso editado correctamente!");
                control.navegarGestionCursos();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El cupo mínimo debe ser número.");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
    * Evento ejecutado
    * al presionar el botón cancelar.
    * 
    * Regresa a la gestión
    * de cursos.
    * 
    * @param evt Evento generado
    * por el botón cancelar.
    */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        control.navegarGestionCursos();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccionarImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCupoMinimo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEditarCurso;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombreDelCurso;
    private javax.swing.JLabel lblPreviwe;
    private javax.swing.JTextField txtCupoMinimo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreDelCurso;
    // End of variables declaration//GEN-END:variables
}
