/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CursoDTO;
import com.mycompany.fitlifegym_dtos.HorarioDTO;
import com.mycompany.fitlifegym_dtos.HorarioDiaSemanaDTO;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class EditarHorarioFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarHorarioFORM.class.getName());
    private final ControlNavegacion control;
    private final CursoDTO curso;

    // ── Constructor 
    public EditarHorarioFORM(ControlNavegacion control, CursoDTO curso) {
        this.control = control;
        this.curso   = curso;
        initComponents();
        this.setLocationRelativeTo(null);
        configurarCombos();
        txtCurso.setText(curso.getNombre());
        txtCurso.setEditable(false);
    }

    // Llenar los combos con datos reales 
    private void configurarCombos() {
        // Dias
        cmbDias.removeAllItems();
        for (HorarioDiaSemanaDTO dia : HorarioDiaSemanaDTO.values()) {
            cmbDias.addItem(dia.name());
        }

        // AM y PM
        cmbAm_Pm.removeAllItems();
        cmbAm_Pm.addItem("AM");
        cmbAm_Pm.addItem("PM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        lblAgregarHorario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        cmbDias = new javax.swing.JComboBox<>();
        lblHoraInicio = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        lblHoraFin = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();
        cmbAm_Pm = new javax.swing.JComboBox<>();
        lblCupoMaximo = new javax.swing.JLabel();
        txtCupoMaximo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));

        lblAgregarHorario.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblAgregarHorario.setForeground(new java.awt.Color(242, 242, 242));
        lblAgregarHorario.setText("EDITAR HORARIO");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Curso:");

        txtCurso.setEditable(false);
        txtCurso.setBackground(new java.awt.Color(99, 99, 99));
        txtCurso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCurso.setForeground(new java.awt.Color(255, 255, 255));

        lblDias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDias.setForeground(new java.awt.Color(242, 242, 242));
        lblDias.setText("Dias:");

        cmbDias.setBackground(new java.awt.Color(99, 99, 99));
        cmbDias.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmbDias.setForeground(new java.awt.Color(255, 255, 255));

        lblHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoraInicio.setForeground(new java.awt.Color(242, 242, 242));
        lblHoraInicio.setText("Hora Inicio:");

        txtHoraInicio.setBackground(new java.awt.Color(99, 99, 99));
        txtHoraInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHoraInicio.setForeground(new java.awt.Color(255, 255, 255));

        lblHoraFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoraFin.setForeground(new java.awt.Color(242, 242, 242));
        lblHoraFin.setText("Hora Fin:");

        txtHoraFin.setBackground(new java.awt.Color(99, 99, 99));
        txtHoraFin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHoraFin.setForeground(new java.awt.Color(255, 255, 255));

        cmbAm_Pm.setBackground(new java.awt.Color(99, 99, 99));
        cmbAm_Pm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cmbAm_Pm.setForeground(new java.awt.Color(255, 255, 255));

        lblCupoMaximo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCupoMaximo.setForeground(new java.awt.Color(242, 242, 242));
        lblCupoMaximo.setText("Cupo Maximo:");

        txtCupoMaximo.setBackground(new java.awt.Color(99, 99, 99));
        txtCupoMaximo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCupoMaximo.setForeground(new java.awt.Color(242, 242, 242));

        btnGuardar.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("+ Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("- Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDias))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbDias, javax.swing.GroupLayout.Alignment.LEADING, 0, 318, Short.MAX_VALUE)
                            .addComponent(txtCurso, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNegroLayout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNegroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNegroLayout.createSequentialGroup()
                                        .addComponent(lblCupoMaximo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCupoMaximo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlNegroLayout.createSequentialGroup()
                                        .addComponent(lblHoraInicio)
                                        .addGap(45, 45, 45)
                                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addComponent(lblHoraFin)
                                .addGap(36, 36, 36)
                                .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addComponent(cmbAm_Pm, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lblAgregarHorario)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregarHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraInicio)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraFin)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAm_Pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCupoMaximo)
                    .addComponent(txtCupoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // ── Validaciones ──────────────────────────────────────────────────
        if (txtHoraInicio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La hora de inicio es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtHoraFin.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La hora de fin es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtCupoMaximo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El cupo máximo es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cmbDias.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un dia.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Construir el DTO 
            String amPm = cmbAm_Pm.getSelectedItem().toString();

            LocalTime horaInicio = parsearHora(txtHoraInicio.getText().trim(), amPm);
            LocalTime horaFin = parsearHora(txtHoraFin.getText().trim(), amPm);

            if (horaInicio.isAfter(horaFin)) {
                JOptionPane.showMessageDialog(this, "La hora de inicio no puede ser después de la hora fin.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<HorarioDiaSemanaDTO> dias = new ArrayList<>();
            dias.add(HorarioDiaSemanaDTO.valueOf(cmbDias.getSelectedItem().toString()));

            HorarioDTO horarioDTO = new HorarioDTO(curso.getIdCurso(), dias, horaInicio, horaFin, Integer.parseInt(txtCupoMaximo.getText().trim()), 0);

            ConfirmacionHorarioFORM confirmacion = new ConfirmacionHorarioFORM(control, horarioDTO);
            confirmacion.setVisible(true);
            this.dispose(); // 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El cupo máximo debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de hora inválido. Usa HH:mm (ej. 9:00)", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // Convierte 9:00 + AM/PM a LocalTime 
    private LocalTime parsearHora(String hora, String amPm) {
        // Acepta "9:00" o "09:00"
        String[] partes = hora.split(":");
        int horas   = Integer.parseInt(partes[0].trim());
        int minutos = partes.length > 1 ? Integer.parseInt(partes[1].trim()) : 0;

        if (amPm.equals("PM") && horas != 12){
            horas += 12;
        }
        if (amPm.equals("AM") && horas == 12){
            horas  = 0;
        }

        return LocalTime.of(horas, minutos);
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAm_Pm;
    private javax.swing.JComboBox<String> cmbDias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgregarHorario;
    private javax.swing.JLabel lblCupoMaximo;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblHoraFin;
    private javax.swing.JLabel lblHoraInicio;
    private javax.swing.JPanel pnlNegro;
    private javax.swing.JTextField txtCupoMaximo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    // End of variables declaration//GEN-END:variables
}
