/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CursoDTO;
import com.mycompany.fitlifegym_presentacion.guardarImagen.GurdadorImagenCarpeta;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 * Formulario encargado
 * de mostrar el mensaje
 * de éxito al guardar un curso.
 * 
 * Permite informar al usuario
 * que el curso fue registrado
 * correctamente en el sistema.
 * 
 * @author PC GAMER MASTER RACE
 */
public class ExitoCursoFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExitoCursoFORM.class.getName());
    private final ControlNavegacion control;
    private final CursoDTO curso;

    /**
    * Constructor del formulario
    * de éxito de curso.
    * 
    * Inicializa los componentes
    * y carga la animación
    * de confirmación.
    * 
    * @param control Controlador
    * de navegación del sistema.
    * @param curso Curso
    * guardado correctamente.
    */
    public ExitoCursoFORM(ControlNavegacion control, CursoDTO curso) {
        this.control = control;
        this.curso = curso;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarPalomita();
    }

    /**
    * Carga la imagen
    * de confirmación
    * dentro del formulario.
    * 
    * Si no encuentra la imagen,
    * muestra una palomita
    * generada por texto.
    */
    private void cargarPalomita() {
        try {
            URL url = getClass().getResource("/palomita.png");
            if (url != null) {
                ImageIcon icon = new ImageIcon(url);
                Image scaled = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
                lblPreviwe.setIcon(new ImageIcon(scaled));
                lblPreviwe.setText("");
            } else {
                lblPreviwe.setText("✓");
                lblPreviwe.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 200));
                lblPreviwe.setForeground(new java.awt.Color(0, 180, 0));
            }
        } catch (Exception e) {
            lblPreviwe.setText("✓");
            lblPreviwe.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 200));
            lblPreviwe.setForeground(new java.awt.Color(0, 180, 0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        lblExito = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCursoGuradadoCorrectamente = new javax.swing.JLabel();
        lblPreviwe = new javax.swing.JLabel();
        btnVolverAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));
        pnlNegro.setForeground(new java.awt.Color(242, 242, 242));

        lblExito.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblExito.setForeground(new java.awt.Color(242, 242, 242));
        lblExito.setText("EXITO");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblCursoGuradadoCorrectamente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCursoGuradadoCorrectamente.setForeground(new java.awt.Color(242, 242, 242));
        lblCursoGuradadoCorrectamente.setText("Curso Guardado Correctamente");

        lblPreviwe.setBackground(new java.awt.Color(64, 64, 64));
        lblPreviwe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreviwe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPreviwe.setOpaque(true);
        lblPreviwe.setPreferredSize(new java.awt.Dimension(150, 130));

        btnVolverAlMenu.setBackground(new java.awt.Color(255, 18, 18));
        btnVolverAlMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolverAlMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAlMenu.setText("Volver Al Menu");
        btnVolverAlMenu.addActionListener(this::btnVolverAlMenuActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(lblExito)
                .addContainerGap(501, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNegroLayout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlNegroLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(lblCursoGuradadoCorrectamente))
                        .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlNegroLayout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(btnVolverAlMenu)))
                    .addContainerGap(334, Short.MAX_VALUE)))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(748, Short.MAX_VALUE))
            .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNegroLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(lblCursoGuradadoCorrectamente)
                    .addGap(48, 48, 48)
                    .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(90, 90, 90)
                    .addComponent(btnVolverAlMenu)
                    .addContainerGap(152, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Evento ejecutado
    * al presionar el botón
    * volver al menú.
    * 
    * Regresa al menú
    * principal del administrador.
    * 
    * @param evt Evento generado
    * por el botón volver.
    */
    private void btnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAlMenuActionPerformed
        control.navegarMenuAdmin();
    }//GEN-LAST:event_btnVolverAlMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAlMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCursoGuradadoCorrectamente;
    private javax.swing.JLabel lblExito;
    private javax.swing.JLabel lblPreviwe;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
