/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 * Formulario encargado
 * de mostrar el mensaje
 * de éxito al guardar un horario.
 * 
 * Permite informar al usuario
 * que el horario fue registrado
 * correctamente en el sistema.
 * 
 * @author PC GAMER MASTER RACE
 */
public class ExitoHorarioFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExitoHorarioFORM.class.getName());
    private final ControlNavegacion control;

    /**
    * Constructor del formulario
    * de éxito de horario.
    * 
    * Inicializa los componentes
    * y carga la animación
    * de confirmación.
    * 
    * @param control Controlador
    * de navegación del sistema.
    */
    public ExitoHorarioFORM(ControlNavegacion control) {
        this.control = control;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarPalomita();
    }

    /**
    * Carga la imagen
    * de confirmación
    * dentro del formulario.
    * 
    * Si no encuentra la imagen,
    * muestra una palomita
    * generada por texto.
    */
    private void cargarPalomita() {
        try {
            //Palomita hardcodeada desde resources
            URL url = getClass().getResource("/palomita.png");
            if (url != null) {
                ImageIcon icon = new ImageIcon(url);
                Image scaled = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
                lblPreviwe.setIcon(new ImageIcon(scaled));
                lblPreviwe.setText("");
            } else {
                //
                lblPreviwe.setText("✓");
                lblPreviwe.setFont(new Font("Segoe UI", Font.BOLD, 200));
                lblPreviwe.setForeground(new Color(0, 180, 0));
            }
        } catch (Exception e) {
            lblPreviwe.setText("✓");
            lblPreviwe.setFont(new Font("Segoe UI", Font.BOLD, 200));
            lblPreviwe.setForeground(new Color(0, 180, 0));
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        lblExito = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHorarioGuradadoCorrectamente = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnVolverAlMenu = new javax.swing.JButton();
        lblPreviwe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));

        lblExito.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblExito.setForeground(new java.awt.Color(242, 242, 242));
        lblExito.setText("EXITO");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        lblHorarioGuradadoCorrectamente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHorarioGuradadoCorrectamente.setForeground(new java.awt.Color(242, 242, 242));
        lblHorarioGuradadoCorrectamente.setText("Horario Guardado Correctamente");

        btnVolverAlMenu.setBackground(new java.awt.Color(255, 18, 18));
        btnVolverAlMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolverAlMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAlMenu.setText("Volver Al Menu");
        btnVolverAlMenu.addActionListener(this::btnVolverAlMenuActionPerformed);

        lblPreviwe.setBackground(new java.awt.Color(64, 64, 64));
        lblPreviwe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreviwe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPreviwe.setOpaque(true);
        lblPreviwe.setPreferredSize(new java.awt.Dimension(150, 130));

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNegroLayout.createSequentialGroup()
                                .addGap(481, 481, 481)
                                .addComponent(lblExito))
                            .addGroup(pnlNegroLayout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(lblHorarioGuradadoCorrectamente))
                            .addGroup(pnlNegroLayout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(lblImagen))
                            .addGroup(pnlNegroLayout.createSequentialGroup()
                                .addGap(336, 336, 336)
                                .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNegroLayout.createSequentialGroup()
                                .addGap(475, 475, 475)
                                .addComponent(btnVolverAlMenu)))
                        .addGap(0, 368, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addComponent(lblExito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorarioGuradadoCorrectamente)
                .addGap(48, 48, 48)
                .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagen)
                .addGap(84, 84, 84)
                .addComponent(btnVolverAlMenu)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Evento ejecutado
    * al presionar el botón
    * volver al menú.
    * 
    * Regresa al menú
    * principal del administrador.
    * 
    * @param evt Evento generado
    * por el botón volver.
    */
    private void btnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAlMenuActionPerformed
        control.navegarMenuAdmin();
    }//GEN-LAST:event_btnVolverAlMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAlMenu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblExito;
    private javax.swing.JLabel lblHorarioGuradadoCorrectamente;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPreviwe;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
