/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class MenuCursosAdminFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCursosAdminFORM.class.getName());
    private ControlNavegacion control;
    /**
     * Creates new form MenuCursosAdmin
     */
    public MenuCursosAdminFORM(ControlNavegacion control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane11 = new javax.swing.JScrollPane();
        textBeneficiario1 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        textBeneficiario3 = new javax.swing.JTextArea();
        lblEstadisticasGenerales = new javax.swing.JLabel();
        lblCursosActivos = new javax.swing.JLabel();
        lblInscripcionesTotales = new javax.swing.JLabel();
        txtCursosActivos = new javax.swing.JTextField();
        txtInscripcionesTotales = new javax.swing.JTextField();
        lblHorariosActivos = new javax.swing.JLabel();
        txtHorariosActivos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGestionCursos1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnREPORTES = new javax.swing.JButton();
        btnGestionHorarios2 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(18, 18, 18));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial", 3, 70)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menu Administrativo");

        jSeparator1.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator1.setForeground(new java.awt.Color(225, 6, 0));

        jScrollPane11.setBorder(null);
        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textBeneficiario1.setBackground(new java.awt.Color(18, 18, 18));
        textBeneficiario1.setColumns(20);
        textBeneficiario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textBeneficiario1.setForeground(new java.awt.Color(255, 255, 255));
        textBeneficiario1.setRows(5);
        textBeneficiario1.setText("  ");
        jScrollPane11.setViewportView(textBeneficiario1);

        jScrollPane13.setBorder(null);
        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textBeneficiario3.setBackground(new java.awt.Color(18, 18, 18));
        textBeneficiario3.setColumns(20);
        textBeneficiario3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textBeneficiario3.setForeground(new java.awt.Color(255, 255, 255));
        textBeneficiario3.setRows(5);
        jScrollPane13.setViewportView(textBeneficiario3);

        lblEstadisticasGenerales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstadisticasGenerales.setForeground(new java.awt.Color(242, 242, 242));
        lblEstadisticasGenerales.setText("Estadisticas Generales:");

        lblCursosActivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCursosActivos.setForeground(new java.awt.Color(242, 242, 242));
        lblCursosActivos.setText("Cursos Activos:");

        lblInscripcionesTotales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInscripcionesTotales.setForeground(new java.awt.Color(242, 242, 242));
        lblInscripcionesTotales.setText("Inscripciones Totales");

        txtCursosActivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCursosActivos.setForeground(new java.awt.Color(255, 255, 255));
        txtCursosActivos.addActionListener(this::txtCursosActivosActionPerformed);

        txtInscripcionesTotales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtInscripcionesTotales.setForeground(new java.awt.Color(255, 255, 255));
        txtInscripcionesTotales.setText("jTextField1");
        txtInscripcionesTotales.addActionListener(this::txtInscripcionesTotalesActionPerformed);

        lblHorariosActivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHorariosActivos.setForeground(new java.awt.Color(242, 242, 242));
        lblHorariosActivos.setText("Horarios Activos:");

        txtHorariosActivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtHorariosActivos.setForeground(new java.awt.Color(255, 255, 255));
        txtHorariosActivos.setText("jTextField1");
        txtHorariosActivos.addActionListener(this::txtHorariosActivosActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Acciones:");

        btnGestionCursos1.setBackground(new java.awt.Color(99, 99, 99));
        btnGestionCursos1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionCursos1.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionCursos1.setText("GESTION CURSOS");
        btnGestionCursos1.addActionListener(this::btnGestionCursos1ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));

        btnREPORTES.setBackground(new java.awt.Color(99, 99, 99));
        btnREPORTES.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnREPORTES.setForeground(new java.awt.Color(255, 255, 255));
        btnREPORTES.setText("REPORTES");
        btnREPORTES.addActionListener(this::btnREPORTESActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnREPORTES)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnREPORTES, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnGestionHorarios2.setBackground(new java.awt.Color(99, 99, 99));
        btnGestionHorarios2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionHorarios2.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionHorarios2.setText("GESTION HORARIOS");
        btnGestionHorarios2.addActionListener(this::btnGestionHorarios2ActionPerformed);

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnGestionCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnGestionHorarios2)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(586, 586, 586)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEstadisticasGenerales))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblCursosActivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCursosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(lblInscripcionesTotales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtInscripcionesTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblHorariosActivos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstadisticasGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCursosActivos)
                    .addComponent(lblInscripcionesTotales)
                    .addComponent(txtCursosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInscripcionesTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorariosActivos)
                    .addComponent(txtHorariosActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGestionCursos1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionHorarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInscripcionesTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInscripcionesTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInscripcionesTotalesActionPerformed

    private void btnGestionCursos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionCursos1ActionPerformed
        GestionDeCursosFORM prueba = new GestionDeCursosFORM(control);
        prueba.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGestionCursos1ActionPerformed

    private void btnREPORTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREPORTESActionPerformed
        GenerarReportesCursosFORM frame = new GenerarReportesCursosFORM(control);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnREPORTESActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestionHorarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionHorarios2ActionPerformed
        GestionHorariosFORM frame = new GestionHorariosFORM(control);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGestionHorarios2ActionPerformed

    private void txtCursosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursosActivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursosActivosActionPerformed

    private void txtHorariosActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorariosActivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorariosActivosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionCursos1;
    private javax.swing.JButton btnGestionHorarios2;
    private javax.swing.JButton btnREPORTES;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCursosActivos;
    private javax.swing.JLabel lblEstadisticasGenerales;
    private javax.swing.JLabel lblHorariosActivos;
    private javax.swing.JLabel lblInscripcionesTotales;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea textBeneficiario1;
    private javax.swing.JTextArea textBeneficiario3;
    private javax.swing.JTextField txtCursosActivos;
    private javax.swing.JTextField txtHorariosActivos;
    private javax.swing.JTextField txtInscripcionesTotales;
    // End of variables declaration//GEN-END:variables
}
