/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 * Formulario encargado
 * de mostrar un mensaje
 * de error al intentar
 * eliminar un horario
 * con inscripciones activas.
 * 
 * Informa al administrador
 * que no es posible realizar
 * la operación solicitada.
 * 
 * @author PC GAMER MASTER RACE
 */
public class NoEliminarHorarioInscripcionesActivasFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NoEliminarHorarioInscripcionesActivasFORM.class.getName());
    private final ControlNavegacion control;

    /**
    * Constructor del formulario
    * de error de eliminación
    * de horario.
    * 
    * Inicializa los componentes
    * y carga la imagen
    * de error.
    * 
    * @param control Controlador
    * de navegación del sistema.
    */
    public NoEliminarHorarioInscripcionesActivasFORM(ControlNavegacion control) {
        this.control = control;
        initComponents();
        cargarPalomita();
    }
    
    /**
    * Carga la imagen
    * de error dentro
    * del formulario.
    * 
    * Si no encuentra
    * la imagen,
    * muestra una tacha
    * generada por texto.
    */
    private void cargarPalomita() {
        try {
            URL url = getClass().getResource("/tacha.png");
            if (url != null) {
                ImageIcon icon = new ImageIcon(url);
                Image scaled = icon.getImage().getScaledInstance(300, 300, Image.SCALE_SMOOTH);
                lblPreviwe.setIcon(new ImageIcon(scaled));
                lblPreviwe.setText("");
            } else {
                lblPreviwe.setText("✗");
                lblPreviwe.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 200));
                lblPreviwe.setForeground(new java.awt.Color(255, 0, 0));
            }
        } catch (Exception e) {
            lblPreviwe.setText("✗");
            lblPreviwe.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 200));
            lblPreviwe.setForeground(new java.awt.Color(255, 0, 0));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblPreviwe = new javax.swing.JLabel();
        btnVolverAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));
        pnlNegro.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("ERROR");

        jSeparator2.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator2.setForeground(new java.awt.Color(225, 6, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("No Se Puede Eliminar El Horario Tiene Inscripciones Activas");

        lblPreviwe.setBackground(new java.awt.Color(64, 64, 64));
        lblPreviwe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreviwe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPreviwe.setOpaque(true);
        lblPreviwe.setPreferredSize(new java.awt.Dimension(150, 130));

        btnVolverAlMenu.setBackground(new java.awt.Color(255, 0, 0));
        btnVolverAlMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVolverAlMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverAlMenu.setText("Volver Al Menu");
        btnVolverAlMenu.addActionListener(this::btnVolverAlMenuActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                        .addContainerGap(8, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                        .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                        .addComponent(btnVolverAlMenu)
                        .addGap(478, 478, 478))))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPreviwe, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(183, 183, 183)
                .addComponent(btnVolverAlMenu)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Evento ejecutado
    * al presionar el botón
    * volver al menú.
    * 
    * Regresa al menú
    * principal del administrador.
    * 
    * @param evt Evento generado
    * por el botón volver.
    */
    private void btnVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAlMenuActionPerformed
        control.navegarMenuAdmin();
    }//GEN-LAST:event_btnVolverAlMenuActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverAlMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPreviwe;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
