/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fitlifegym_presentacion;

import com.mycompany.fitlifegym_dtos.CursoDTO;
import com.mycompany.fitlifegym_dtos.HorarioDTO;
import com.mycompany.fitlifegym_presentacion.guardarImagen.GurdadorImagenCarpeta;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author PC GAMER MASTER RACE
 */
public class YaEstasInscritoFORM extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(YaEstasInscritoFORM.class.getName());
    private final ControlNavegacion control;
    private final CursoDTO curso;
    private final HorarioDTO horario;

    public YaEstasInscritoFORM(ControlNavegacion control, CursoDTO curso, HorarioDTO horario) {
        this.control = control;
        this.curso = curso;
        this.horario = horario;
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarInfoHorario();
    }

    // Muestra el horario en el que ya esta inscrito
    private void mostrarInfoHorario() {
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
        jPanel1.setBackground(new Color(18, 18, 18));
        jPanel1.removeAll();

        // Imagen del curso
        JLabel lblImagen = new JLabel();
        lblImagen.setPreferredSize(new java.awt.Dimension(200, 150));
        lblImagen.setMaximumSize(new java.awt.Dimension(200, 150));
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        lblImagen.setAlignmentX(Component.CENTER_ALIGNMENT);
        lblImagen.setBackground(new Color(40, 40, 40));
        lblImagen.setOpaque(true);

        if (curso != null && curso.getImagen() != null && curso.getImagen().getRuta() != null && !curso.getImagen().getRuta().isEmpty()) {
            ImageIcon icon = GurdadorImagenCarpeta.cargarImagen(curso.getImagen().getRuta(), 200, 150);
            if (icon != null) {
                lblImagen.setIcon(icon);
            } else {
                lblImagen.setText("Sin imagen");
                lblImagen.setForeground(Color.GRAY);
            }
        } else {
            lblImagen.setText("Sin imagen");
            lblImagen.setForeground(Color.GRAY);
        }

        // Nombre del curso
        JLabel lblNombre = new JLabel(curso != null ? curso.getNombre().toUpperCase() : "");
        lblNombre.setForeground(Color.WHITE);
        lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblNombre.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Dias
        String dias = "";
        if (horario != null && horario.getDias() != null) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < horario.getDias().size(); i++) {
                String d = horario.getDias().get(i).toString();
                sb.append(d.length() >= 2 ? d.substring(0, 2) : d);
                if (i < horario.getDias().size() - 1) sb.append(" - ");
            }
            dias = sb.toString();
        }

        JLabel lblDias = new JLabel(dias);
        lblDias.setForeground(Color.WHITE);
        lblDias.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblDias.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Horario
        String horaStr = "--:-- - --:--";
        if (horario != null && horario.getHoraInicio() != null && horario.getHoraFin() != null) {
            horaStr = horario.getHoraInicio() + " - " + horario.getHoraFin();
        }

        JLabel lblHora = new JLabel(horaStr);
        lblHora.setForeground(new Color(225, 6, 0));
        lblHora.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblHora.setAlignmentX(Component.CENTER_ALIGNMENT);

        jPanel1.add(Box.createVerticalStrut(30));
        jPanel1.add(lblImagen);
        jPanel1.add(Box.createVerticalStrut(15));
        jPanel1.add(lblNombre);
        jPanel1.add(Box.createVerticalStrut(10));
        jPanel1.add(lblDias);
        jPanel1.add(Box.createVerticalStrut(8));
        jPanel1.add(lblHora);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNegro = new javax.swing.JPanel();
        lbYaEstasInscrito = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnVerMisCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNegro.setBackground(new java.awt.Color(18, 18, 18));

        lbYaEstasInscrito.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lbYaEstasInscrito.setForeground(new java.awt.Color(242, 242, 242));
        lbYaEstasInscrito.setText("YA ESTAS INSCRITO A ESTE CURSO");

        jSeparator2.setBackground(new java.awt.Color(225, 6, 0));
        jSeparator2.setForeground(new java.awt.Color(225, 6, 0));

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1443, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        btnVerMisCursos.setBackground(new java.awt.Color(255, 0, 0));
        btnVerMisCursos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerMisCursos.setForeground(new java.awt.Color(255, 255, 255));
        btnVerMisCursos.setText("Ver Mis Cursos");
        btnVerMisCursos.addActionListener(this::btnVerMisCursosActionPerformed);

        javax.swing.GroupLayout pnlNegroLayout = new javax.swing.GroupLayout(pnlNegro);
        pnlNegro.setLayout(pnlNegroLayout);
        pnlNegroLayout.setHorizontalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addGroup(pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(lbYaEstasInscrito)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlNegroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNegroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerMisCursos)
                .addGap(625, 625, 625))
        );
        pnlNegroLayout.setVerticalGroup(
            pnlNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNegroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbYaEstasInscrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(btnVerMisCursos)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMisCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMisCursosActionPerformed
        control.navegarVerMiscursos();
    }//GEN-LAST:event_btnVerMisCursosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerMisCursos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbYaEstasInscrito;
    private javax.swing.JPanel pnlNegro;
    // End of variables declaration//GEN-END:variables
}
